<?php

class SyncPullApiRequest
{
	const ERROR_TARGET_POST_NOT_FOUND = 100;
	const ERROR_POST_NOT_FOUND = 101;
	const ERROR_POST_TYPE_NOT_FOUND = 102;
	const ERROR_SEARCH_NOT_FOUND = 103;
	const ERROR_CANNOT_CREATE_NEW_POST = 104;

	const NOTICE_CONTENT_MODIFIED = 100;
	const NOTICE_CANNOT_UPLOAD = 101;
	const NOTICE_FILE_ERROR = 102;
}

// EOF