<?php

class SyncPullApiRequest
{
	const ERROR_TARGET_POST_NOT_FOUND = 100;
	const ERROR_POST_NOT_FOUND = 101;

	const NOTICE_CONTENT_MODIFIED = 100;
	const NOTICE_CANNOT_UPLOAD = 101;
	const NOTICE_FILE_ERROR = 102;
}

// EOF